services:
  run:
    name: Run
    description: Runs the bot
    triggeredBy:
      - manual
    commands:
      start: bun run run-dev
  prisma:
    name: Prisma Studio
    description: Runs Prisma Studio to inspect the database
    triggeredBy:
      - manual
    commands:
      start: bun run prisma-studio
tasks:
  init:
    name: Initialize
    description: Initialize workspace and database
    triggeredBy:
      - postDevcontainerStart
    command: |
      bun install
      bun run build
      bun run migrate
  check:
    name: Check
    description: Runs formatting, linters, and tests
    triggeredBy:
      - manual
    command: bun run checks
