services:
  run:
    name: Run
    description: Runs the bot
    triggeredBy:
      - manual
    commands:
      start: npm run run-dev
  prisma:
    name: Prisma Studio
    description: Runs Prisma Studio to inspect the database
    triggeredBy:
      - manual
    commands:
      start: npm run prisma-studio
tasks:
  init:
    name: Initialize
    description: Initialize workspace and database
    triggeredBy:
      - postDevcontainerStart
    command: |
      npm install
      npm run build
      npm run migrate
      curl -fsSL https://bun.sh/install | bash
  check:
    name: Check
    description: Runs formatting, linters, and tests
    triggeredBy:
      - manual
    command: npm run checks
