name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Remove dev dependencies
        run: npm ci --omit=dev

      - name: Install SSH Key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
          echo ${{ secrets.KNOWN_HOSTS }} >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Stop
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: ssh jannis@jannis.rocks 'forever stop /home/jannis/parmelae-bot/dist/index.js || true'

      - name: Deploy
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: rsync -chilOrz --stats --delete --include node_modules --include dist --exclude-from .gitignore --exclude .git ./ jannis@jannis.rocks:/home/jannis/parmelae-bot/

      - name: Start
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: ssh jannis@jannis.rocks 'cd /home/jannis/parmelae-bot/ && npm run migrate-prod && forever start --workingDir /home/jannis/parmelae-bot/ /home/jannis/parmelae-bot/dist/index.js'

      - name: Remove SSH
        run: rm -rf ~/.ssh
