name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Remove dev dependencies
        run: bun run install-prod

      - name: Install SSH Key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
          echo ${{ secrets.KNOWN_HOSTS }} >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Stop
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: ssh jannis@jannis.rocks 'forever stop /home/jannis/parmelae-bot/dist/index.js || true'

      - name: Deploy
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: rsync -chilOrz --stats --delete --include node_modules --include dist --exclude-from .gitignore --exclude .git ./ jannis@jannis.rocks:/home/jannis/parmelae-bot/

      - name: Start
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: ssh jannis@jannis.rocks 'cd /home/jannis/parmelae-bot/ && npm run migrate-prod && forever start --workingDir /home/jannis/parmelae-bot/ /home/jannis/parmelae-bot/dist/index.js'

      - name: Remove SSH
        run: rm -rf ~/.ssh
