name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run checks (type check, lint, test)
        run: bun run checks

      - name: Remove dev dependencies
        run: bun run install-prod

      - name: Install SSH Key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
          echo ${{ secrets.KNOWN_HOSTS }} >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Create database backup
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          echo "Ensuring backup directory exists and creating database backup..."
          ssh jannis@jannis.rocks 'cd /home/jannis/parmelae-bot && mkdir -p backups && bun scripts/backup/backup-database.ts'
          if [ $? -ne 0 ]; then
            echo "❌ Database backup failed"
            exit 1
          fi
          echo "✅ Database backup completed"

      - name: Cleanup old backups
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          echo "Cleaning up old backups..."
          ssh jannis@jannis.rocks 'cd /home/jannis/parmelae-bot && bun scripts/backup/cleanup-backups.ts'
          echo "✅ Backup cleanup completed"

      - name: Stop bot (PM2)
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: ssh jannis@jannis.rocks 'cd /home/jannis/parmelae-bot && pm2 stop parmelae-bot || true'

      - name: Deploy files
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: rsync -chilOrz --stats --delete --exclude .git --exclude .gitignore --exclude prisma/sqlite.db --exclude .env --exclude .cursor --exclude .devcontainer --exclude .github --exclude .taskmaster --exclude .vscode --exclude backups ./ jannis@jannis.rocks:/home/jannis/parmelae-bot/

      - name: Run database migrations
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: ssh jannis@jannis.rocks 'cd /home/jannis/parmelae-bot && bun run migrate-prod'

      - name: Start bot (PM2)
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: ssh jannis@jannis.rocks 'cd /home/jannis/parmelae-bot && pm2 start ecosystem.config.cjs'

      - name: Remove SSH
        if: always()
        run: rm -rf ~/.ssh
